### ISSUE TITLE
How get regid after register

### ISSUE THREAD

**Issue by mapeveri** [zckrs/cordova-plugin-push-notification#5]
Hi, how can get regid after register. I have this code:

```
      var pushNotification = window.plugins.pushNotification;
      pushNotification.register(successHandler, errorHandler, {"senderID":"myprojectnumber", "ecb":"onNotification"});


      function errorHandler (error) {
          $scope.msjpush = "Error: " + error;
      }

      function successHandler (result) {
         $scope.msjpush = "Success: " + result;
      }

     // handle GCM notifications for Android
     function onNotification(e) {
       switch(e.event){
             case 'registered':
          if (e.regid.length > 0){
                      $scope.msjpush = e.regid;
           }
              break;
         case 'message':
               $scope.msjpush = "Message";
                break;
         }
      }
```

But never enter the function onNotification. I use android.

Thanks!

**Comment by kumaresan-cgvak** [comment]
@mapeveri Try to execute the following line inside device ready.

 pushNotification.register(successHandler, errorHandler, {"senderID":"myprojectnumber", "ecb":"onNotification"});

**Comment by mapeveri** [comment]
@kumaresan-cgvak hi, i have this code:

```
function onDeviceReady(){
    try {
        var pushNotification = window.plugins.pushNotification;
         pushNotification.register(successHandler, errorHandler, {"senderID":"myprojectnumber", "ecb":"onNotification"});
    } catch (e){
         $scope.msjpush = "Error notification push: " + e;
    }
  }

   function errorHandler (error) {
    $scope.msjpush = "Error: " + error;
  }

  function successHandler (result) {
    $scope.msjpush = "Success: " + result;
  }

  function onNotification(e) {
    switch(e.event){
      case 'registered':
        $scoope.msjpush = "Registered";
                if (e.regid.length > 0){
                    // Your GCM push server needs to know the regID before it can push to this device
                    // here is where you might want to send it the regID for later use.
                    $scope.msjpush = e.regid;
          $scope.ref.child("users/" + btoa($scope.user.email)).update({gcm_id: e.regid});
                }
        break;
      case 'message':
        $scope.msjpush = "message";
        break;
    }
  }      

  document.addEventListener('deviceready', onDeviceReady, true);
```

And return "success ok", but no insert regid in firebase. No enter in he function onNotification

Thank you!

**Comment by kumaresan-cgvak** [comment]
@mapeveri Have you modified the sender id with your Project id?

**Comment by mapeveri** [comment]
@kumaresan-cgvak Yes, my project number is my senderId, in my code not have "myprojectnumber" if not the original "project number" of the console google. Any idea?.

Thanks so much!

**Comment by kumaresan-cgvak** [comment]
Try commenting all the lines inside onNotification and just add an alert and check

**Comment by mapeveri** [comment]
@kumaresan-cgvak Does nothing :(

**Comment by kumaresan-cgvak** [comment]
@mapeveri Can you tell me the Device configuration details like OS version etc

**Comment by mapeveri** [comment]
@kumaresan-cgvak Yes, my os version is Android 4.1.2, version kernel 3.4.0. 

This apis I have enabled:

![image](https://cloud.githubusercontent.com/assets/6276555/12236320/dcffae28-b857-11e5-86bf-d2f987e38234.png)

This key i have:

![image](https://cloud.githubusercontent.com/assets/6276555/12236347/fece764c-b857-11e5-8616-b3e36c0e0da3.png)

Any data more you need?.

**Comment by mapeveri** [comment]
@kumaresan-cgvak hey my friend, i have this error in the console chrome (web view). The code before, return this error in the console:

Uncaught (in promise) ReferenceError: onNotification is not defined
    at eval (eval at processMessage (file:///android_asset/www/cordova.js:1068:22), <anonymous>:1:12)
    at processMessage (file:///android_asset/www/cordova.js:1068:9)
    at processMessages (file:///android_asset/www/cordova.js:1102:9)

But that function is declared.

Any idea?.

Thanks!

**Comment by mapeveri** [comment]
I found the problem, i am use Ionic and ionic use angular. I have one controller like this.

```
(function(){
     "use strict";
      angular.module('MyApp')
        .controller('MyController', function($scope){
             //My functions... One of these functions executes the register
         });
   })();
```

For that execute method onNotification my code should look likemy code:

```
 (function(){
     "use strict";
      angular.module('MyApp')
        .controller('MyController', function($scope){
             //My functions... One of these functions executes the register
         });
   })();

   function onNotification(e){
       console.log("onNotification")
    }
```

But this does not help me, because I can not enter the object $scope of angular. Any idea?.

Thank so much for all the help and patience :+1:

**Comment by kumaresan-cgvak** [comment]
@mapeveri Are you executing app in device?

**Comment by kumaresan-cgvak** [comment]
you can try to change the function 

```
function onNotification(e){
       console.log("onNotification")
    }
```

to 

```
 $scope.onNotification = function (e) {

  };
```

also modify it in during registration.

**Comment by kumaresan-cgvak** [comment]
Please find the details regarding the error that you got in browser :

Cordova/Phonegap is not supported in browser. So browser throws an error. :100:

**Comment by mapeveri** [comment]
@kumaresan-cgvak hi, this not found:

```
 $scope.onNotification = function (e) {

 };
```

Same error "ReferenceError: onNotification is not defined". More details that this error not have. The console with crosswalk return that error.

Apparently the problem is the scope of my role no?.

```
  (function(){
       // some code…
   })();
```
